name: Publish NuGet Package

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # 또는 net9.0 사용 중이면 '9.0.x'

      - name: Build and pack
        run: |
          echo "##1"
          pwd
          ls
          cd CreamsLib
          echo "##2"
          pwd
          ls
          dotnet pack --configuration Release

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push CreamsLib/bin/Release/*.nupkg \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key ${{ secrets.GITHUB_TOKEN }}
